# Generated by Django 3.0.4 on 2020-03-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feed',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='feed',
            new_name='data',
        ),
    ]
